apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: addresspool
  namespace: metallb-system
spec:
  addresses:
    - 192.168.4.200-192.168.4.222
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2advertisement
  namespace: metallb-system